version: "3.7"
services:

  dbms:
    image: postgres
    environment:
      TZ: ${OS_TIMEZONE}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d postgres -U postgres"]
      interval: 10s
      timeout: 10s
      retries: 5
    ports:
      - ${DB_PORT}:5432

  dbadmin:
    image: dockage/phppgadmin
    depends_on: 
      - dbms
    environment:
      PHP_PG_ADMIN_SERVER_HOST: dbms
      PHP_PG_ADMIN_SERVER_PORT: ${DB_PORT}
      TZ: ${OS_TIMEZONE}
    ports:
      - ${ADMIN_PORT}:80

  dbdoc:
    image: schemaspy/schemaspy
    environment: 
      TZ: ${OS_TIMEZONE}
    volumes: 
      - ./target/classes/schemaspy.properties:/schemaspy.properties
      - ./target/schemaspy:/output
